### ISSUE TITLE
Ajax Cart Popup Issue

### ISSUE THREAD

**Issue by anku1234** [husseycoding/ajaxcartpopup#11] opened 2015-10-12 13:56 UTC

**Comment by husseycoding** [comment] 2015-10-12 14:26
Can you please provide as much detail as possible about the issue you are experiencing with steps to reproduce?

**Comment by anku1234** [comment] 2015-10-13 03:58
Hi
Issue is with minicart dropdown on hover. Its not working properly in some of the pages of site.

**Comment by Nico10** [comment] 2015-10-13 07:20
Hi,

Could you please provide a url link to where the issue is happening so we can have a look at it.

Thanks

**Comment by anku1234** [comment] 2015-10-13 07:58
http://www.pyxistechnologies.com.au/doodle/index.php/checkout/cart/
http://www.pyxistechnologies.com.au/doodle/index.php/checkout/onepage/

And Some where the dropdown is showing half page down
Please find the image below for the second point
![issuse1](https://cloud.githubusercontent.com/assets/14919480/10448977/2cb677d0-71ae-11e5-83bd-253fc43e1c2f.png)

**Comment by husseycoding** [comment] 2015-10-13 08:10
The popup not working on the cart/checkout pages is by design - doesn't make sense to have the mini cart popup display when you are on the already looking at the cart contents or have decided to checkout.

Also the popup attaches to an anchor element with a class of either `top-link-cart` or 'skip-cart' - dependant on theme.  If this element is not in the right place when the mini cart popup is initialised then the popup will be in the wrong place - sounds like this is probably what is happening for you.

Can you provide steps to reliably reproduce the issue where you see the mini cart popup show halfway down the page?  Doesn't seem to be doing that for me.

**Comment by husseycoding** [comment] 2015-10-15 17:05
Not enough information to go on here so closing the issue, just add some more information if you have any and we can take another look.

**Closed by husseycoding** 2015-10-15 17:05 UTC
Labels: invalid

**Comment by anku1234** [comment] 2015-10-16 05:10
Sir i have a problem

On changing quantity on cart dropdown It dosent change quantity. Please
find the image below to know what I'm Taking about.

On Thu, Oct 15, 2015 at 10:35 PM, Jonathan Hussey <notifications@github.com>
wrote:

> Closed #11 <https://github.com/husseycoding/ajaxcartpopup/issues/11>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/husseycoding/ajaxcartpopup/issues/11#event-436634762>.
>



-- 

*Regards:*
*Ankush Rana*
*--------------*
*Multi Dimension Web Marketing Pvt. Ltd.*

**Comment by husseycoding** [comment] 2015-10-16 06:21
There just isn't enough information here, if you are able to give more detail with steps to reproduce issues then we can take another look.

**Comment by anku1234** [comment] 2015-10-20 09:56
Hi Sir

Hope You doing Well

I struct with an Another issue. While dropdown if minicart i cant update
quantity. Please Help Me regarding This ASAP

On Fri, Oct 16, 2015 at 11:51 AM, Jonathan Hussey <notifications@github.com>
wrote:

> There just isn't enough information here, if you are able to give more
> detail with steps to reproduce issues then we can take another look.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/husseycoding/ajaxcartpopup/issues/11#issuecomment-148625577>
> .
>



-- 

*Regards:*
*Ankush Rana*
*--------------*
*Multi Dimension Web Marketing Pvt. Ltd.*

**Comment by husseycoding** [comment] 2015-10-20 10:05
I have just tested quantity changing in the mini cart and it is working correctly for me.  You need to provide steps to reproduce any issues you are seeing.

**Comment by anku1234** [comment] 2015-10-20 10:10
http://www.pyxistechnologies.com.au/doodle/

Please visit the above link

Go to category page i.e Clothing

Add product to cart

Then visit in minicart dropdown

There you will see input type field for quantity. If i change Quantity
there it doesn't change quantity.

On Tue, Oct 20, 2015 at 3:35 PM, Jonathan Hussey <notifications@github.com>
wrote:

> I have just tested quantity changing in the mini cart and it is working
> correctly for me. You need to provide steps to reproduce any issues you are
> seeing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/husseycoding/ajaxcartpopup/issues/11#issuecomment-149506887>
> .
>



-- 

*Regards:*
*Ankush Rana*
*--------------*
*Multi Dimension Web Marketing Pvt. Ltd.*

**Comment by husseycoding** [comment] 2015-10-20 10:33
You need to press enter after you have changed the quantity, are you doing that?

**Comment by husseycoding** [comment] 2015-10-20 10:38
I'm locking this conversation, if you have any more issues you will need to open another issue.
